### ISSUE TITLE
Unhandled 'error' event while processing SVG

### ISSUE THREAD

**Issue by sbouchex** [tancredi/fantasticon#132]
Running fantasticon 1.1.1 on Windows and processing the attached SVG.

executed line : fantasticon src -o dist -n sgdf

I'm getting a sax.js parsing error :

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Invalid character entity
Line: 12
Column: 53
Char: ;
    at error (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:677:7)
    at parseEntity (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:937:7)
    at SAXParser.write (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:1485:31)
    at SAXStream.write (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:239:18)
    at ReadStream.ondata (internal/streams/readable.js:719:22)
    at ReadStream.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at ReadStream.Readable.push (internal/streams/readable.js:223:10)
Emitted 'error' event on SVGIcons2SVGFontStream instance at:
    at SAXStream.<anonymous> (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\svgicons2svgfont\src\index.js:348:12)
    at SAXStream.emit (events.js:327:22)
    at SAXParser.SAXStream._parser.onerror (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:194:10)
    at emit (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:624:35)
    at error (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:653:5)
    at strictFail (C:\Users\Sébastien\AppData\Roaming\npm\node_modules\fantasticon\node_modules\sax\lib\sax.js:677:7)
    [... lines matching original stack trace ...]
    at ReadStream.ondata (internal/streams/readable.js:719:22)
```

[SIGNES_JAMBVILLE_abeille 1.zip](https://github.com/tancredi/fantasticon/files/6057390/SIGNES_JAMBVILLE_abeille.1.zip)

**Comment by lknop** [comment]
@sbouchex the reason for this is that the svg contains nonstandard Adobe Illustrator extensions and the svg parser fantasticon is using is in running in strict mode.

A similar issue can be found here for svgo project: https://github.com/svg/svgo/issues/272

The solution given there should also be valid for you - disable "Preserve Illustrator Editing Capabilities" when saving the svg.
