### ISSUE TITLE
Is there a plan to support ligatures?

### ISSUE THREAD

**Issue by thepian** [tancredi/fantasticon#182]
As described in https://github.com/Workshape/icon-font-generator/issues/12#issuecomment-310371294

**Comment by oscargm** [comment]
Hello,

I've created a MR to add a proposal to add ligatures.

Inspired by the comment of @thepian , I've digged into webfonts-generator code and looked to where it adds the ligature [here](https://github.com/sunflowerdeath/webfonts-generator/blob/master/src/generateFonts.js#L54).

I've done the changes locally and I've run the tests, I'm aware that they're failing, but so far I think that the returned value is "correct" considering the changes on the asset generation.

```bash
Summary of all failing tests
 FAIL  generators/asset-types/__tests__/svg.ts
  ● `SVG` font generator › resolves with the result of the completed `SVGIcons2SVGFontStream`

    expect(received).toMatchSnapshot()

    Snapshot name: `\`SVG\` font generator resolves with the result of the completed \`SVGIcons2SVGFontStream\` 1`

    Snapshot: "processed->content->/root/foo.svg|{\"name\":\"foo\",\"unicode\":[\"\\u0001\"]}$processed->content->/root/bar.svg|{\"name\":\"bar\",\"unicode\":[\"\\u0001\"]}$"
    Received: "processed->content->/root/foo.svg|{\"name\":\"foo\",\"unicode\":[\"\\u0001\",\"foo\"]}$processed->content->/root/bar.svg|{\"name\":\"bar\",\"unicode\":[\"\\u0001\",\"bar\"]}$"

      77 |     });
      78 | 
    > 79 |     expect(result).toMatchSnapshot();
         |                    ^
      80 |   });
      81 | 
      82 |   test('passes correctly format options to `SVGIcons2SVGFontStream`', async () => {

      at generators/asset-types/__tests__/svg.ts:79:20
      at fulfilled (generators/asset-types/__tests__/svg.ts:24:58)

  ● `SVG` font generator › passes correctly format options to `SVGIcons2SVGFontStream`

    expect(received).toMatchSnapshot()

    Snapshot name: `\`SVG\` font generator passes correctly format options to \`SVGIcons2SVGFontStream\` 1`

    Snapshot: "processed->content->/root/foo.svg|{\"name\":\"foo\",\"unicode\":[\"\\u0001\"]}$processed->content->/root/bar.svg|{\"name\":\"bar\",\"unicode\":[\"\\u0001\"]}$"
    Received: "processed->content->/root/foo.svg|{\"name\":\"foo\",\"unicode\":[\"\\u0001\",\"foo\"]}$processed->content->/root/bar.svg|{\"name\":\"bar\",\"unicode\":[\"\\u0001\",\"bar\"]}$"

      85 |     const result = await svgGen.generate(mockOptions(formatOptions), null);
      86 | 
    > 87 |     expect(result).toMatchSnapshot();
         |                    ^
      88 | 
      89 |     expect(SVGIcons2SVGFontStream).toHaveBeenCalledTimes(1);
      90 |     expect(SVGIcons2SVGFontStream).toHaveBeenCalledWith({

      at generators/asset-types/__tests__/svg.ts:87:20
      at fulfilled (generators/asset-types/__tests__/svg.ts:24:58)
```

Let me know if I miss something or there is something else to take into account.
I've seen that TTF depends on SVG, and woff, woff2 depend on TTF, so that's why i only changed SVG generator.

It'd be really nice to have ligatures creation added into the library.
Also adding an option in options to allow ligature enabling/disabling is on my mind (but as a next steps if everything looks corect for you).

**Comment by oscargm** [comment]
If @tancredi don't see anything wrong, PR should be mergeable.

I've added:

- ligatures to svg generator
- An option named `addLigatures` to options to be able to enable ligatures (false by default).

And fixed all the tests, SVG generator is tested with and without ligatures.
