### ISSUE TITLE
Which platform are you using?

### ISSUE THREAD

**Issue by tec-lab** [tancredi/fantasticon#4]
I tried on Ubuntu 18 LTS but failed at installation:

```
tombert@DESKTOP-APKU8T8:~/cm$ sudo npm install -g fantasticon
[sudo] password for tombert:
npm WARN deprecated transformation-matrix-js@2.7.6: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/fantasticon -> /usr/local/lib/node_modules/fantasticon/bin/fantasticon

> ttf2woff2@3.0.0 install /usr/local/lib/node_modules/fantasticon/node_modules/ttf2woff2
> ((node-gyp configure && node-gyp build) > builderror.log) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/tombert/.node-gyp/8.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/fantasticon/node_modules/ttf2woff2/.node-gyp"
make: *** No rule to make target '../.node-gyp/8.10.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/fantasticon/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
```

On Rasp OS it installs but then I get a runtime error: 
```
[20:51:49] openhabian@openHABianDevice:/etc/openhab2/webshare$ fantasticon -n -r svg/*
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '../lib/cli'
Require stack:
- /etc/openhab2/webshare/fantasticon/bin/fantasticon
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/etc/openhab2/webshare/fantasticon/bin/fantasticon:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
```

thx!

**Comment by tancredi** [comment]
Hi @tec-lab - which version of Node are you using?

**Comment by tec-lab** [comment]
Ubuntu 18 LTS (which fails installation) runs node 8.10.0
Rasp OS (which installs, but fails to run) runs node 12.19.0

**Comment by tec-lab** [comment]
got it running on U18
